export const USER_LOOKUP_START = 'USER_LOOKUP_START';
export const USER_LOOKUP_FINISH = 'USER_LOOKUP_FINISH';
export const USER_LOOKUP_FAILURE = 'USER_LOOKUP_FAILURE';
export const USER_CLEAR_ERROR = 'USER_CLEAR';
export const USER_CLEAR = 'USER_CLEAR_ERROR';
export const USER_LOGOUT = 'USER_LOGOUT';

export const ROOMS_LOADING_START = 'FETCH_ROOMS';
export const ROOMS_LOADING_FINSIH = 'FETCH_ROOMS_FINSIH';
export const ROOMS_FAILURE = 'ROOMS_FAILURE';
export const ROOMS_CLEAR_ERROR = 'ROOMS_CLEAR_ERROR';

export const ROOM_LOADING_START = 'ROOM_LOADING_START';
export const ROOM_LOADING_FINSIH = 'ROOM_LOADING_FINSIH';
export const ROOM_FAILURE = 'ROOM_FAILURE';
export const ROOM_CLEAR_ERROR = 'ROOM_CLEAR_ERROR';
export const ROOM_CLEAR_FINSIH = 'ROOM_CLEAR_FINSIH';
export const ROOM_ADD_MEMBER = 'ROOM_ADD_MEMBER';
export const ROOM_REMOVE_MEMBER = 'ROOM_REMOVE_MEMBER';

export const TOKEN_LOADING_START = 'TOKEN_LOADING_START';
export const TOKEN_GENERATION_FINISH = 'TOKEN_ADD_FINISH';
export const TOKEN_REMOVE_FINISH = 'TOKEN_REMOVE_FINISH';
export const TOKEN_CLEAR_FINISH = 'TOKEN_CLEAR_FINISH';
export const TOKEN_FAILURE = 'TOKEN_FAILURE';
export const TOKEN_CLEAR_ERROR = 'TOKEN_CLEAR_ERROR';
