export const FETCH_START = "FETCH_START";
export const FETCH_SUCCESS = "FETCH_SUCCESS";
export const FETCH_FAILURE = "FETCH_FAILURE";

export const USER_LOOKUP_START = "USER_LOOKUP_START";
export const USER_LOOKUP_FINISH = "USER_LOOKUP_FINISH";
export const USER_LOOKUP_FAILURE = "USER_LOOKUP_FAILURE";
export const USER_CLEAR_ERROR = "USER_CLEAR_ERROR";
export const USER_LOGOUT = "USER_LOGOUT";
