export enum UserRole {
  Admin = "ADMIN",
  User = "USER",
  Guest = "GUEST",
}

export enum IconId {
  ArrowRight = "ARROW_RIGHT",
  Call = "CALL",
  CallSolid = "CALL_SOLID",
  Chart = "CHART",
  Check = "CHECK",
  CheckCircle = "CHECK_CIRCLE",
  DangerCircle = "DANGER_CIRCLE",
  DangerSquareSm = "DANGER_SQUARE_SM",
  Document = "DOCUMENT",
  Globe = "GLOBE",
  HandGear = "HAND_GEAR",
  InfoSquareSm = "INFO_SQUARE_SM",
  Instagram = "INSTAGRAM",
  LampGear = "LAMP_GEAR",
  Message = "MESSAGE",
  MessageSolid = "MESSAGE_SOLID",
  Moon = "MOON",
  SuccessSquareSm = "SUCCESS_SQUARE_SM",
  Sun = "SUN",
  Twitter = "TWITTER",
  WarningSquareSm = "WARNING_SQUARE_SM",
  Search = "SEARCH",
}
