export enum UserRole {
  Admin = 'ADMIN',
  User = 'USER',
  Guest = 'GUEST',
}

export enum IconId {
  ArrowRight = 'ARROW_RIGHT',
  Call = 'CALL',
  CallSolid = 'CALL_SOLID',
  Chart = 'CHART',
  Check = 'CHECK',
  CheckCircle = 'CHECK_CIRCLE',
  Compass = 'COMPASS',
  DangerCircle = 'DANGER_CIRCLE',
  DangerSquareSm = 'DANGER_SQUARE_SM',
  Document = 'DOCUMENT',
  Globe = 'GLOBE',
  HandGear = 'HAND_GEAR',
  InfoSquareSm = 'INFO_SQUARE_SM',
  Instagram = 'INSTAGRAM',
  Key = 'KEY',
  LampGear = 'LAMP_GEAR',
  Lock = 'LOCK',
  Login = 'LOGIN',
  Logout = 'LOGOUT',
  Message = 'MESSAGE',
  MessageSolid = 'MESSAGE_SOLID',
  Moon = 'MOON',
  Notification = 'NOTIFICATION',
  PlusCircle = 'PLUS_CIRCLE',
  Profile = 'PROFILE',
  Search = 'SEARCH',
  SuccessSquareSm = 'SUCCESS_SQUARE_SM',
  Sun = 'SUN',
  Twitter = 'TWITTER',
  UserSolid = 'USER_SOLID',
  Voice = 'VOICE',
  WarningSquareSm = 'WARNING_SQUARE_SM',
  VoiceSolid = 'VOICE_SOLID',
  VoiceOffSolid = 'VOICE_OFF_SOLID',
}
